# Generated by Django 6.0.7 on 2026-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster', models.URLField()),
                ('backdrop', models.URLField(blank=True)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
